---
title: "05 - Ejercicios - Tendencia central y varianza"
output: 
  html_notebook: 
    toc: true
---

# Estudiante: SuNombre

Para realizar estos ejercicios use como referencia el documento "05 - Tendencia central y varianza.Rmd".

Resuelva estos ejercicios en este documento insertando los chuncks necesarios (cntrl + alt + i), luego de cada consigna. Agregue al nombre del archivo el suyo al final (05 - Ejercicios - Tendencia central y varianza - SuNombre Apellido.Rmd), y me lo envía por email.

Cargue las librerías necesaria cuando las necesite, no lo haga al inicio de la actividad. Esto no es el modo habitual de trabajo, pero se pretende aquí que usted descubra cuándo necesita las librerías extra.

## Experimento

Existen experimentos manipulativos o mensurativos. 

Los manipulativos son aquellos en los que manipulamos algo y medimos variables sobre lo manipulado. Por ejemplo, regamos plantas de tomate con dos cantidades diferentes de agua y cierto tiempo depués medimos altura, peso, cantidad de hojas, cantidad de flores, cantidad de frutos, peso de los frutos, etc. de las plantasde tomate en ambos tratamientos. 

Los experimentos mensurativos en cambio, consisten en observar y medir algo "como está", y buscamos en la realidad un experimento que se haya hecho espontáneamente. Por ejemplo, encuestamos personas que hayan comprado en dos supermercados diferentes y les preguntamos qué compraron, cuánto compraron, qué faltó en el supermercado, qué decidieron no comprar, etc.

En esta oportunidad usted debe realizar un experimento de cualquiera de los dos tipos y medir al menos 2 variables contínuas y dos discretas. Registre la información, organícela y luego cárguela para ser usada en R.

En clases es conveniente que todos tengan la misma información a analizar, por esa razón en esta oportunidad le recomiendo que diseñen la actividad en grupos o inclusive todo el curso completo. Es importante para esta actividad involucrarse activamente en el diseño del experimento, la toma de datos y la digitalización de los mismos. Por esta última razón es preferible trabajar en grupos chicos si el trabajo entre todos le impide involucrarse activamente (trabajar de a muchos es difícil).

La intensión no es lograr un experimento perfecto, trate de hacerlo lo mejor posible, pero es la primera vez y por lo tanto imposible que salga todo bien. Que las dificultades no sean un impedimento, avance aunque haya problemas y registre todo lo que le resulte importante, incluso los intentos fallidos.

## Cargar la información

-   Describa el experimento y las variables medidas. Describa cómo midió todo lo que midió. Describa cómo eligió lo que decidió medir.
-   Cree un tibble con la información recopilada.

# Descripción de las muestras

Todos los índices siguientes deben calcularse sobre cada variable cuantitativa (contínua o discreta) del tibble creado.

## Medidas de tendencia Central

-   Mediana
-   Moda
-   Media

## Medidas de variación

-   Mínimo
-   Máximo
-   Cuantiles
-   Varianza
-   Desvío Estándar
-   Coeficiente de Variación
-   Error Estándar
-   Asimetría
-   Kurtosis
-   Intervalo de confianza

## Toda la información en un tibble

-   Todos los índices en un solo tibble. Esto permite exportar la información ordenada.

## Gráficos

-   Histogramas
-   Densidad
-   Probabilidad acumulada
-   Box Plot y violín

# Sugerencias

En el siguiente sitio hay varios test de reflejos, memoria etc. que podrían realizar varias veces cada uno y recopilar datos de esta manera. Obviamente debe haber infinidad de este tipo de sitios, puede elejir el que le resulte más adecuado.
https://www.arealme.com/apm-actions-per-minute-test/es/

En realidad el sitio anterior tiene muchos otros tipos de tests que podría usar.
https://www.arealme.com/es

Puede recopilar una serie de objetos similares (por ejemplo plantas), y medirle varias cosas a cada una (como altura, peso, cantidad de hojas, cantidad de flores).

Armar una encuesta por teléfono que tenga 4 preguntas, 2 para responder con números reales, y 2 con números enteros. Ejemplo, ¿Cuántas veces por día se sienta a comer?, ¿Cuántos días por semana come usted carne?, Estime cuánta agua consume por día (en litros), ¿Cuánto tiempo promedio dedica cada vez que se sienta a comer? (en minutos), etc. Una encuesta así puede armarse con los formularios de google. Aquí un ejemplo: <https://docs.google.com/forms/d/e/1FAIpQLSee2VpYipwupnrGSA1Iz3m7_wNtoq_UHquwPa-ApN3WxVcefA/viewform?usp=sf_link>

Podría pararse en una esquina transitada de 9 de Julio y contar cuántas personas viajan en cada auto que pase durante un rato, cuánto tiempo transcurre entre la pasada de un auto y el siguiente, cantidad de autos que pasan en un período de tiempo fijo, generar categorías de vehículos (bicicleta, moto, auto, camioneta, etc.) y contar cuántos pasan de cada uno en un período de tiempo fijo, si hace marcas en el asfalto puede medir tiempos en recorrer cierta distancia y así calcular la velocidad, etc. Este experimento puede repetirse en diferentes momentos del día.

Los ejemplos anteriores son para inducir su imaginación, hay infinidad de cosas para medir. Sólo piense en algo que le genere curiosidad y luego pregúntese qué y cómo puede medirlo. Inténte algo que le divierta aunque no salga como esperaba.
