---
title: "06 - Descriptiva basica"
output: html_notebook 
---

`Falta ordenar y titular`

```{r}
library(tidyverse)
# library(crosstable)
library(ggplot2)
library(GGally)
```

```{r}
diamonds
```

```{r fig.height=10, fig.width=12, message=FALSE, warning=FALSE}
diamonds %>% 
  subset(y < 20) %>% subset(z < 10) %>% # para quitar 3 puntos outliers
  ggpairs(columns = c(1,5:10), aes(color = cut, alpha = 0.5))
# ggpairs(diamonds, aes(color = cut, alpha = 0.5))
```

```{r}
gr1 <- ggplot(diamonds, aes(depth)) + 
  geom_histogram()
gr1
```

```{r}
unaTablita <- table(cut(diamonds$depth, breaks = c(54,56,58,60,62,64,66,68,70)))
prop.table(unaTablita)
unaTablita
```
```{r}
# CrossTable(diamonds$color, diamonds$cut, prop.t=TRUE, prop.r=TRUE, prop.c=TRUE)
```

  
```{r}
summary(diamonds)
```

```{r fig.height=10, fig.width=12}
gr2 <- ggplot(diamonds, aes(x = color, y = carat)) + 
  geom_boxplot() +
  facet_grid(rows = vars(cut), cols = vars(clarity))
gr2
```

```{r fig.height=10, fig.width=12}
gr3 <- ggplot(diamonds, aes(x = carat, y = depth)) + 
  geom_violin() +
#    geom_dotplot() +
  facet_grid(rows = vars(color), cols = vars(clarity))
gr3
```

## iris

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}


irisTidy <- tibble(iris)
nombres <- c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width")
irisTidy <- irisTidy %>% pivot_longer(all_of(nombres), names_to = "Variable", values_to = "valor")
irisTidy
```

Se puede calcular los índices que se desee a cada grupo de interés

Creamos algunas funciones que realizan cálculos que nos interesen:

```{r}
library(plotrix) 

q1 <- function(data) {
  quantile(data, probs = 0.25)[[1]]
  # también podría ser fivenum(data)[2]
}
q2 <- function(data) {
  quantile(data, probs = 0.5)[[1]]
  # también podría ser fivenum(data)[3]
}
q3 <- function(data) {
  quantile(data, probs = 0.75)[[1]]
  # también podría ser fivenum(data)[4]
}

ic95 <- function(data) {
  c(mean(data)-1.96*std.error(data),mean(data)+1.96*std.error(data))
}
```

Creamos un nuevo data set con los índices que nos interese comparar.

```{r}
indicesIris <- irisTidy %>% group_by(Species,Variable) %>% reframe(n = n(), media = mean(valor), q1 = q1(valor), mediana = median(valor),q3 = q3(valor), sd = sd(valor), varianza = var(valor), cv = sd/media, EE = std.error(valor), "IC95-" = ic95(valor)[1], "IC95+" = ic95(valor)[2])
indicesIris
```