source("funciones/calcularMediana.R")
source("funciones/moda.R")
source("funciones/quantiles.R")
source("funciones/factorialRecursivo.R")
source("funciones/ic95.R")
source("funciones/cv.R")
source("funciones/datosAtipicos.R")
